### ISSUE TITLE
Update doc for 3.0.15 to mention values loaded from other fields no longer show empty values

### ISSUE THREAD

**Issue by benkeen** [formtools/docs#12]
As described.

**Comment by AdStaak** [comment]
Great news! Does this include not showing items that are not finalised yet? If you selected an unfinalised entry in the past (most of the time such an item would be empty, but not necessarily), the referenced item would be automatically deleted if the item is not finalised within a specific time. So you were referencing a non existing item in the end. I just finished creating a reporting page to detect such entries in my forms, so I can fix them. If they will not occur again, that's just great!

**Comment by benkeen** [comment]
Ooh drat, thanks! You're absolutely right it should omit those entries. I'll fix that up too.
