### ISSUE TITLE
Broken link in tutorial on adding POST form (https://docs.formtools.org/tutorials/adding_post_form/)

### ISSUE THREAD

**Issue by tomstreeter** [formtools/docs#15]
Step #6 points to https://docs.formtools.org/tutorials/adding_post_form/step_5/ instead of /step_6/

**Comment by benkeen** [comment]
Thanks @tomstreeter, I'll patch this up soon.

**Comment by benkeen** [comment]
This has been updated in the repo. Next time I update the doc on the main website (should be soon, I'm almost done the next Core version) this'll be included.
